version: 2.1
workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context:
            - drupal
      - pantheon/push:
          requires:
            - build
          context:
            - drupal
          checkout: false
          terminus_clone_env: live
          clone_content: false
          env_create_max_time: "15m"
          pre-steps:
            - checkout
            - attach_workspace:
                at: .
      - diffy:
          requires:
            - pantheon/push
          context:
            - drupal
          filters:
            branches:
              ignore:
                - main

orbs:
  diffy: diffy/diffy@0.0.2
  # Pantheon Orb source and README: https://github.com/pantheon-systems/circleci-orb
  # More Pantehon Orb Docs https://circleci.com/developer/orbs/orb/pantheon-systems/pantheon
  pantheon: pantheon-systems/pantheon@0.6.0
jobs:
  build:
    docker:
      - image: docksal/cli:2.11-php7.4
        user: docker
    # resource_class: xlarge
    working_directory: /var/www
    steps:
      - run:
          name: Prepare /var/www for Docksal image environment
          command: |
            sudo rmdir html
            sudo chown docker: /var/www

      - checkout
    # Steps to build the theme ar whatever needed before deployment.

  diffy: diffy/compare_multidev_dev