name: Test PRs MultiDev and Diffy

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      - name: Deploy to MultiDev
        env:
          pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
          pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
        run: |
          BASE_BRANCH=${GITHUB_REF##*/}
          git remote add pantheon $pantheon_repo
          git push pantheon HEAD:master
          commit_hash=$(git log -1 --pretty=%H)
          terminus multidev:create $pantheon_site_name.live $BASE_BRANCH
      - name: Cache rebuild, import configuration
        env:
          pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
        run: |
          BASE_BRANCH=${GITHUB_REF##*/}
          terminus remote:drush $pantheon_site_name.$BASE_BRANCH cr
          terminus remote:drush $pantheon_site_name.$BASE_BRANCH config:import -y
      - name: Trigger Diffy testing
        run: |
          MULTIDEV_SITE_URL='https://$BASE_BRANCH-$pantheon_site_name.pantheonsite.io/'
          # Download Diffy-CLI.
          wget https://github.com/diffywebsite/diffy-cli/releases/latest/download/diffy.phar

          # Authenticate.
          php diffy.phar auth:login $DIFFY_API_KEY

          # Compare with commit sha so Diffy's github check posts the results. 
          LAST_GIT_COMMIT_HASH=$(git log -1 --pretty=%H)
          php diffy.phar project:compare $DIFFY_PROJECT_ID dev custom --env2Url="${MULTIDEV_SITE_URL}" --commit-sha="${LAST_GIT_COMMIT_HASH}"

