name: Test PRs MultiDev and Diffy

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ secrets.SSH_CONFIG }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      - name: Deploy to MultiDev
        env:
          pantheon_repo: '${{ secrets.PANTHEON_REPO }}'
          pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
          pr_number: ${{ github.event.number }}
        run: |
          PR_BRANCH="pr-$pr_number"
          git remote add pantheon $pantheon_repo
          git fetch pantheon
          git push --force pantheon HEAD:refs/heads/$PR_BRANCH
          terminus multidev:create $pantheon_site_name.live $PR_BRANCH
      - name: Cache rebuild, import configuration
        env:
          pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
          pr_number: ${{ github.event.number }}
        run: |
          PR_BRANCH="pr-$pr_number"
          terminus remote:drush $pantheon_site_name.$PR_BRANCH cr
          terminus remote:drush $pantheon_site_name.$PR_BRANCH config:import -y
      - name: Trigger Diffy testing
        env:
          diffy_api_key: '${{ secrets.DIFFY_API_KEY }}'
          diffy_project_id: '${{ secrets.DIFFY_PROJECT_ID }}'
          pantheon_site_name: '${{ secrets.PANTHEON_SITE_NAME }}'
          pr_number: ${{ github.event.number }}
        run: |
          PR_BRANCH="pr-$pr_number"
          MULTIDEV_SITE_URL="https://$PR_BRANCH-$pantheon_site_name.pantheonsite.io/"
          # Download Diffy-CLI.
          wget https://github.com/diffywebsite/diffy-cli/releases/latest/download/diffy.phar

          # Authenticate.
          php diffy.phar auth:login $diffy_api_key

          # Compare with commit sha so Diffy's github check posts the results. 
          LAST_GIT_COMMIT_HASH=$(git log -1 --pretty=%H)
          php diffy.phar project:compare $diffy_project_id dev custom --env2Url="${MULTIDEV_SITE_URL}" --commit-sha="${LAST_GIT_COMMIT_HASH}"

